os: osx
osx_image: xcode7.3
language: swift
install:
    - gem install bundler
    - bundle install
    - brew update
    - brew install carthage
    - carthage bootstrap --verbose --platform 'iOS' --no-use-binaries
script:
    - bundle exec rake specs
