os: osx
osx_image: xcode7.3
language: swift
install:
    - gem install bundler
    - bundle install
    - brew update
    - brew install carthage
    - mkdir Carthage
    - mkdir Carthage/Checkouts
    - git clone https://github.com/Quick/Nimble.git Carthage/Checkouts/Nimble
    - git clone https://github.com/Quick/Quick.git Carthage/Checkouts/Quick
    - git clone https://github.com/Swinject/Swinject.git Carthage/Checkouts/Swinject
    - git clone https://github.com/jwfriese/Fleet.git Carthage/Checkouts/Fleet
    - carthage build --verbose --platform 'iOS'
script:
    - bundle exec rake specs
